name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo $PWD
      - name: docker build 
        run: cd ../..
      - name: docker build 
        run: sudo docker-compose build
      - name: docker up
        run: sudo docker-compose up -d
      - name: test commmand  
        run: sudo docker-compose exec php bin/phpunit


